name: Generate & Upload Documentation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  document:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Generate documentation
        uses: lunarmodules/ldoc@v1.5.0
        with:
          args: "--dir docs --all ."
          
      - name: Upload documentation artifact
        uses: actions/upload-artifact@v3
        with:
          name: documentation
          path: docs/
      
      - name: Upload to Wiki
        uses: Decathlon/wiki-page-creator-action@v2.0.2
        env:
          ACTION_MAIL: richie0415@hotmail.com
          ACTION_NAME: Ceriole
          GH_PAT: ${{ secrets.GH_PAT }}
          MD_FOLDER: docs
          OWNER: Ceriole
          REPO_NAME: BugSpeak
          SKIP_MD: README.md